fix(wallet): make hasCurrentUserBackupInCloud fallback to false on CloudPermissionFailedException (#2113)
## Description
App fails to get `hasCurrentUserBackupInCloud` value because of the
`CloudPermissionFailedException`, which leads to a crashed section on
the Wallets page. Part of the stacktrace:
```
[Flutter Error] ParallelWaitError: IONException(code: 10073, message: Not signed in for cloud account or permission denied)
ParallelWaitError: IONException(code: 10073, message: Not signed in for cloud account or permission denied)
StackTrace: #1      AsyncError.value (package:riverpod/src/common.dart:495:7)
common.dart:495
#2      useOnReceiveFundsFlow (package:ion/app/hooks/use_on_receive_funds_flow.dart:13:84)
use_on_receive_funds_flow.dart:13
#3      BalanceActions.build (package:ion/app/features/wallets/views/pages/wallet_page/components/balance/balance_actions.dart:27:27)
```

Now the provider just returns `false` in case of the
`CloudPermissionFailedException`.


## Type of Change
- [x] Bug fix

## Screenshots (if applicable
<img width="350" alt="image"
src="https://github.com/user-attachments/assets/7206c69e-5360-4173-b5c3-f9b0131e0d4d"
/>